[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from   = "/nvd-api/*"
  to     = "https://services.nvd.nist.gov/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/cisa-api/*"
  to     = "https://www.cisa.gov/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
